# Generated by Django 5.1.6 on 2025-02-15 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ControlledBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DriveBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Forklift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('engine_serial_number', models.CharField(max_length=100)),
                ('transmission_serial_number', models.CharField(max_length=100)),
                ('drive_bridge_serial_number', models.CharField(max_length=100)),
                ('controlled_bridge_serial_number', models.CharField(max_length=100)),
                ('supply_contract_number', models.CharField(max_length=100)),
                ('supply_contract_date', models.DateField()),
                ('shipment_date', models.DateField()),
                ('consignee', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=255)),
                ('configuration', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('controlled_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_bridge', to='forklifts.bridgemodel')),
                ('drive_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_bridge', to='forklifts.bridgemodel')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_model', to='forklifts.enginemodel')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.enginemodel')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_companies', to=settings.AUTH_USER_MODEL)),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.transmissionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField()),
                ('operating_hours', models.FloatField()),
                ('failure_description', models.TextField()),
                ('used_parts', models.TextField()),
                ('recovery_date', models.DateField()),
                ('downtime', models.FloatField(editable=False)),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_companies_complaints', to=settings.AUTH_USER_MODEL)),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.failurenode')),
                ('forklift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.forklift')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.recoverymethod')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('operating_hours', models.FloatField()),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('forklift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.forklift')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.organization')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_companies_maintenance', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.servicetype')),
            ],
        ),
    ]
