# Generated by Django 5.1.6 on 2025-02-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklifts', '0003_alter_forklift_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forklift',
            name='supply_contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forklift',
            name='supply_contract_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
