# Generated by Django 5.1.6 on 2025-02-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklifts', '0005_alter_forklift_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalservice',
            name='service_company',
        ),
        migrations.AlterField(
            model_name='technicalservice',
            name='organization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technicalservice',
            name='service_type',
            field=models.CharField(max_length=100),
        ),
    ]
